### ISSUE TITLE
Question about the input of shallow nerf network

### ISSUE THREAD

**Issue by shoutOutYangJie** [PeterouZh/CIPS-3D#18]
I know nerf is a view-dependent synthesis method due to a direction input.
However, in your code. I find you don't use it. Why can cips3d still work? just input the world coordinate can achieve new view synthesis? why?

**Comment by shoutOutYangJie** [comment]
I know nerf is a view-dependent synthesis method due to a direction input. 
However, in your code. I find you don't use it. Why can it work? just input the world coordinate can achieve new view synthesis? why?

**Comment by PeterouZh** [comment]
As stated in the original NeRF paper, the direction input helps NeRF recreate specular reflection. Without the direction, NeRF can still represent 3D scenes but may decrease the model's ability. 

I don't use direction as input because I empirically found that the input direction will cause the face identity to be inconsistent under multiple views.

Although we did not input the direction, we can still obtain multi-view images by changing the camera's pose. Imagine that you are observing a stationary object that is in the world coordinate from different positions (your eyes are equivalent to a camera).
