### ISSUE TITLE
Quantitative evaluation

### ISSUE THREAD

**Issue by AustinXY** [PeterouZh/CIPS-3D#4]
Do you have quantitative evaluations of the model on some other datasets (compcar or afhq)? If so, how do they compare to StyleNeRF results?

**Comment by PeterouZh** [comment]
I have fine-tuned an AFHQ model from the FFHQ model. Since the NeRF network is frozen, the 3D shape is learned from face dataset. As such, the performance is limited. 

When I am free, I will train a model on AFHQ from scratch. I think it will not be more difficult compared to human faces. 

As for compcar, the hyperparameters may need to be re-adjusted. I currently have no plans to do this experiment.
